workflows:
  default-workflow:
    name: Face Swapper Pro Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Parse all_in_one_code.md
        script: |
          echo ">>> Parsing all_in_one_code.md"
          python3 <<'EOF'
          import os, re, sys

          with open("all_in_one_code.md", encoding="utf-8") as f:
              content = f.read()

          blocks = re.split(r"## FILE:", content)[1:]
          for block in blocks:
              lines = block.strip().splitlines()
              filename = lines[0].strip()
              code = "\n".join(lines[1:]).strip()
              if code.startswith("```"):
                  code = "\n".join(code.splitlines()[1:-1])  # strip fences
              os.makedirs(os.path.dirname(filename), exist_ok=True)
              with open(filename, "w", encoding="utf-8") as f:
                  f.write(code.strip())

          # safety check
          if not os.path.exists("mobile_app/pubspec.yaml"):
              print("WARNING: pubspec.yaml missing, creating fallback")
              os.makedirs("mobile_app", exist_ok=True)
              with open("mobile_app/pubspec.yaml", "w") as f:
                  f.write("name: face_swapper_pro\ndescription: Auto fallback pubspec\nversion: 1.0.0\n")
          EOF

      - name: Flutter Pub Get
        working_directory: mobile_app
        script: |
          flutter pub get

      - name: Flutter Build
        working_directory: mobile_app
        script: |
          flutter build apk --release

    artifacts:
      - mobile_app/build/app/outputs/flutter-apk/app-release.apk
